import React, {useEffect, useRef, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Phone, PhoneOff, Mic, Send, Headphones, Check, ArrowUpRight, Volume2, VolumeX, ShieldCheck, Activity, RefreshCw, NotebookPen, Receipt, Download} from 'lucide-react';
import Voice from './voice.js';
import Call from './call.js';
import {NOTE_LABELS, clock, started, receiptText, filename} from './record.js';
import NeuralVoice from './neural-voice.js';
import Dashboard from './Dashboard.jsx';
import './style.css';

const terminal=new Set(['completed','declined','suppressed','human','callback','ended']);
const snapshots={supply:{postcode:'2000',fuel:'electricity'}, postcode:{postcode:'2000'}, property:{postcode:'2000',fuel:'electricity',occupancy:'rent',solar:false}, empty:{}};
const scenarios=[['Human request',"I'd like to speak to a human"],['Frustration',"I've already told three of you my details"],['Do not call','Stop calling me'],['Confusion','I do not understand what you mean'],['Distress',"I'm overwhelmed and can't cope with this right now"],['Privacy','Where did you get my number?'],['Hardship',"I can't afford my energy bills"],['Accessibility',"I'm hard of hearing. Please speak slowly"],['Language',"I don't speak English"],['Connection','The line is breaking up'],['Payment',"I'd like to pay by card"],['Advice','Which plan should I choose?'],['Busy',"I'm in a meeting"],['Negated request',"I don't need a human"]];
const friendly=value=>String(value??'').replaceAll('_',' ');
function App(){
 const [token,setToken]=useState('local-demo'),[script,setScript]=useState(null),[session,setSession]=useState(null),[snapshot,setSnapshot]=useState('supply');
 const [busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[text,setText]=useState(''),[voice,setVoice]=useState(true),[listening,setListening]=useState(false),[scenario,setScenario]=useState(0);
 const [lookup,setLookup]=useState(''),[number,setNumber]=useState(''),[dialConfirm,setDialConfirm]=useState(false);
 const [voiceEngine,setVoiceEngine]=useState('neural'),[voiceStatus,setVoiceStatus]=useState('');
 const [onCall,setOnCall]=useState(false),[stage,setStage]=useState(''),[caption,setCaption]=useState('');
 const neural=useRef(null),audioElement=useRef(null),tokenRef=useRef(token),engineRef=useRef(voiceEngine);
 const player=useRef(null),recognition=useRef(null),flight=useRef(false),latest=useRef(null),speechEnabled=useRef(true),scroll=useRef(null);
 const call=useRef(null),calling=useRef(false),handlers=useRef({});
 latest.current=session; speechEnabled.current=voice; tokenRef.current=token; engineRef.current=voiceEngine;
 useEffect(()=>{
   const done=()=>handlers.current.resume?.();
   player.current=new Voice({synthesis:window.speechSynthesis,Utterance:window.SpeechSynthesisUtterance,onDone:done});
   neural.current=new NeuralVoice({audio:audioElement.current,getToken:()=>tokenRef.current,onStatus:setVoiceStatus,onDone:done});
   call.current=new Call({Recognition:window.SpeechRecognition||window.webkitSpeechRecognition,onCaption:setCaption,
     onStage:setStage,onError:setNotice,onFinal:(value,confidence)=>handlers.current.send?.(value,confidence)});
   return()=>{player.current.cancel();neural.current.cancel();call.current.close();recognition.current?.abort();};
 },[]);
 useEffect(()=>{const transcript=scroll.current?.parentElement;transcript?.scrollTo({top:transcript.scrollHeight,behavior:'smooth'});},[session?.revision,session?.id,caption]);
 const cancelSpeech=()=>{player.current?.cancel();neural.current?.cancel();};
 // Hand the line back to the caller once a reply has actually finished playing, as on a real call.
 const resume=()=>{if(!calling.current)return;const current=latest.current;
   if(!current||terminal.has(current.state)){calling.current=false;setOnCall(false);call.current?.close();return;}
   call.current?.listen();};
 const speak=s=>{if(speechEnabled.current&&s.state!=='human'&&s.message){if(engineRef.current==='neural')neural.current.speak(s);else player.current.speak(s.message);}else resume();};
 const api=async(path,body)=>{const response=await fetch(path,{method:body?'POST':'GET',headers:{'Content-Type':'application/json',Authorization:`Bearer ${tokenRef.current}`},body:body?JSON.stringify(body):undefined});const value=await response.json();if(!response.ok)throw new Error(value.error||'Request failed');return value;};
 const work=async(fn)=>{if(flight.current)return;flight.current=true;setBusy(true);setNotice('');try{await fn();}catch(e){setNotice(e.message);}finally{flight.current=false;setBusy(false);}};
 const apply=(s,read=true)=>{setSession(s);latest.current=s;if(read)speak(s);else resume();};
 const hangUp=()=>{calling.current=false;setOnCall(false);setStage('');setCaption('');call.current?.close();cancelSpeech();};
 const endCurrent=async()=>{hangUp();const current=latest.current;if(current&&!terminal.has(current.state)&&!current.call_sid)apply(await api('/api/end',{session_id:current.id}),false);};
 const endCall=()=>work(endCurrent);
 const start=()=>work(async()=>{recognition.current?.abort();await endCurrent();setScript(await api('/api/scripts'));apply(await api('/api/sessions',{seed:snapshots[snapshot]}));setText('');});
 // A hands-free call: the assistant speaks, the microphone reopens by itself, and the turn is sent on a pause.
 const startCall=()=>work(async()=>{recognition.current?.abort();await endCurrent();setScript(await api('/api/scripts'));
   const opened=call.current.open();const fresh=await api('/api/sessions',{seed:snapshots[snapshot]});
   if(opened){calling.current=true;setOnCall(true);}
   setText('');apply(fresh);});
 // Click a lead in the queue: same hands-free live call, seeded with that lead's name.
 const callLead=(lead)=>work(async()=>{recognition.current?.abort();await endCurrent();setScript(await api('/api/scripts'));
   const opened=call.current.open();const fresh=await api('/api/sessions',{lead_id:lead.id});
   if(opened){calling.current=true;setOnCall(true);}
   setText('');apply(fresh);});
 // A turn that cannot be sent must still hand the line back, or the call would stall with a closed microphone.
 const send=(value,confidence=null)=>{if(flight.current)return resume();
   return work(async()=>{const current=latest.current;if(!current||terminal.has(current.state))return resume();
     call.current?.hold();cancelSpeech();
     apply(await api('/api/turn',{session_id:current.id,text:value,event_id:crypto.randomUUID(),revision:current.revision,confidence}));setText('');});};
 const load=()=>work(async()=>{cancelSpeech();setScript(await api('/api/scripts'));apply(await api('/api/sessions/'+encodeURIComponent(lookup.trim())),false);});
 const refresh=()=>work(async()=>{cancelSpeech();if(session)apply(await api('/api/sessions/'+session.id),false);});
 const action=route=>work(async()=>{cancelSpeech();apply(await api('/api/'+route,{session_id:session.id}),route!=='accept');if(route==='accept')setNotice('Simulated acceptance. No telephone audio bridge is created in the browser.');});
 const listen=()=>{cancelSpeech();if(calling.current){call.current.listen();return;}const Recognition=window.SpeechRecognition||window.webkitSpeechRecognition;if(!Recognition){setNotice('Speech recognition is unavailable. Use text input or a supported browser.');return;}recognition.current?.abort();const r=new Recognition();recognition.current=r;r.lang='en-AU';r.interimResults=false;r.continuous=false;r.onstart=()=>setListening(true);r.onend=()=>setListening(false);r.onresult=e=>{const result=e.results[0][0];send(result.transcript,result.confidence>0?result.confidence:null);};r.onerror=e=>{setNotice('Microphone: '+e.error+'. You can still type.');setListening(false);};r.start();};
 const dial=()=>work(async()=>{const result=await api('/api/dial',{session_id:session.id,number});setDialConfirm(false);setNotice('Telephone call requested: '+result.status);apply(await api('/api/sessions/'+session.id),false);});
 handlers.current={send,resume}; // The call loop always drives the current turn handler, never a stale one.
 const ended=!session||terminal.has(session.state),active=session?.active_script,field=active?.field;
 const micOn=listening||stage==='listening';
 const notes=session?.notes||[],base=notes.length?notes[0].at:0,summary=session?.summary;
 const download=()=>{const blob=new Blob([receiptText(summary)],{type:'text/plain'});const url=URL.createObjectURL(blob);
   const link=document.createElement('a');link.href=url;link.download=filename(summary);link.click();URL.revokeObjectURL(url);};
 const stageLabel={connecting:'Connecting…',listening:'Listening to the caller…',holding:'Assistant speaking…',thinking:'Assistant is thinking…'}[stage]||'';
 return <div className="app"><aside className="rail"><a className="logo" href="/" aria-label="Phonease home"><Phone size={23}/></a><span className="rail-active"><Headphones size={22}/></span><span className="rail-bottom"><ShieldCheck size={21}/></span></aside><div className="shell">
 <header><div className="wordmark">phonease<span> / workspace</span></div><span className="environment"><i/> Synthetic workspace</span><label className="token">API token<input aria-label="API token" type="password" autoComplete="off" value={token} onChange={e=>setToken(e.target.value)}/></label></header>
 <main><div className="page-title"><div><p className="eyebrow">ENERGY RECOVERY</p><h1>Dashboard</h1><p>Your leads, AI calls and human handoffs at a glance.</p></div><span className="operator"><Headphones size={18}/> Operator console</span></div>
 <Dashboard token={token} sessionId={session?.id} revision={session?.revision} onCallLead={callLead} busy={busy}/>
 <div className="workspace"><section className="panel conversation"><div className="panel-heading"><div><span className="eyebrow">LIVE CONVERSATION</span><h2>Energy assistant</h2></div><span className={'badge '+(session?.state==='completed'?'success':'')}>{session?friendly(session.state):'Ready'}</span></div>
 <div className="call-setup"><label>Resume from<select value={snapshot} onChange={e=>setSnapshot(e.target.value)} disabled={busy}><option value="supply">Energy type saved · property next</option><option value="postcode">Postcode saved · energy type next</option><option value="property">Property saved · moving next</option><option value="empty">No saved answers</option></select></label><button className="primary" onClick={startCall} disabled={busy}><Phone size={16}/> Start call <ArrowUpRight size={16}/></button><button onClick={start} disabled={busy}>Text only</button></div>
 <div className="voice-bar"><button onClick={listen} disabled={ended||busy} className={micOn?'listening':''}><Mic size={16}/>{micOn?'Listening…':onCall?'Interrupt & speak':'Speak / interrupt'}</button>{onCall&&<button className="hangup" onClick={endCall} disabled={busy}><PhoneOff size={16}/> Hang up</button>}<button aria-pressed={voice} onClick={()=>{speechEnabled.current=!voice;setVoice(!voice);if(voice)cancelSpeech();}}>{voice?<Volume2 size={16}/>:<VolumeX size={16}/>} Spoken replies {voice?'on':'off'}</button>{session&&<button className="icon-button" onClick={refresh} disabled={busy} aria-label="Refresh session"><RefreshCw size={16}/></button>}</div>
 <div className="voice-settings"><label>Reply voice<select aria-label="Reply voice" value={voiceEngine} disabled={busy} onChange={e=>{cancelSpeech();setVoiceEngine(e.target.value);}}><option value="neural">OpenAI neural voice</option><option value="device">Device voice (offline)</option></select></label><button disabled={!session||busy||!voice||listening||session.state==='human'} onClick={()=>{if(voiceEngine==='neural')neural.current.replay(session);else speak(session);}}>Replay reply</button></div>
 <audio ref={audioElement} preload="auto"/>
 {onCall&&<p className={'call-stage '+(stage||'idle')} role="status"><i/>{stageLabel||'On a call'}</p>}
 <p className="voice-status" role="status">{voiceStatus||(voiceEngine==='neural'?'AI-generated voice · OpenAI neural speech':'AI-generated voice · browser/OS speech')}</p>
 <div className="transcript" aria-live="polite">{!session?<div className="empty"><div className="soundwave">▂ ▄ ▆ ▃ █ ▅ ▂ ▆ ▃</div><h3>Ready to listen.</h3><p>Choose a saved journey and start a conversation.<br/>The assistant asks for consent before collecting answers.</p></div>:session.events.filter(e=>['caller','assistant'].includes(e.kind)).map((event,i)=><div className={'bubble '+event.kind} key={i}><small>{event.kind==='caller'?'CALLER':'PHONEASE ASSISTANT'}</small><p>{event.content}</p></div>)}{caption&&<div className="bubble caller live"><small>CALLER · LIVE</small><p>{caption}</p></div>}<div ref={scroll}/></div>
 <form className="reply" onSubmit={e=>{e.preventDefault();send(text);}}><input aria-label="Caller reply" placeholder={onCall?'Or type a caller reply…':'Type a caller reply…'} maxLength={1200} disabled={ended||busy} value={text} onChange={e=>setText(e.target.value)}/><button className="primary" aria-label="Send reply" disabled={ended||busy||!text.trim()}><Send size={18}/></button></form>
 <div className="examples"><span className="eyebrow">TRY A SCENARIO</span><div>{scenarios.slice(0,3).map(([label,value])=><button key={label} disabled={ended||busy} onClick={()=>send(value)}>{label}</button>)}</div><div className="scenario-select"><select aria-label="Example scenario" value={scenario} onChange={e=>setScenario(Number(e.target.value))}>{scenarios.map(([label],i)=><option value={i} key={label}>{label}</option>)}</select><button disabled={ended||busy} onClick={()=>send(scenarios[scenario][1])}>Try example</button></div></div>
 <p className="notice" role="status">{busy?'Working…':notice}</p><p className="footnote">On a call the microphone stays open between replies and the turn is sent after a short pause; typing works at any time. Use synthetic details. This is an AI-generated voice, not a human. Neural replies send assistant text to OpenAI and incur usage charges. Speech input may use your browser’s speech service. No caller audio is recorded by Phonease.</p></section>
 <aside className="side"><section className="panel memory"><div className="panel-heading"><div><span className="eyebrow">JOURNEY MEMORY</span><h2>Confirmed, not assumed.</h2></div><ShieldCheck size={22}/></div><div className="fields">{(script?.fields||[{key:'postcode',label:'Supply postcode'},{key:'fuel',label:'Energy type'},{key:'occupancy',label:'Occupancy'},{key:'solar',label:'Solar panels'},{key:'moving',label:'Moving home'}]).map(f=><div className="field" key={f.key}><span>{f.label}</span><strong className={session?.fields[f.key]?'captured':'missing'}>{session?.fields[f.key]?<><Check size={14}/>{String(session.fields[f.key].value)}</>:'Awaiting answer'}</strong></div>)}</div><p className="callout">{session?.pending?`Needs confirmation: ${session.pending.field} → ${session.pending.value}`:'Answers are saved after caller confirmation.'}</p><p className="footnote receipt">{session?.receipt?'✓ Submitted to local mock · '+session.receipt.id:'All fields and a final yes are required to submit.'}</p></section>
 <section className="panel notes"><div className="panel-heading"><div><span className="eyebrow">LIVE CALL NOTES</span><h2>Noted while you talk.</h2></div><NotebookPen size={21}/></div>
 <div className="note-console" aria-live="polite">{notes.length?notes.map((note,i)=><div className={'note '+note.kind} key={i}><span className="note-time">{clock(note.at,base)}</span><span className="note-kind">{NOTE_LABELS[note.kind]||note.kind}</span><p>{note.text}</p></div>):<p className="muted">Notes appear here as the caller confirms details or raises something. Nothing the caller says is quoted.</p>}</div>
 <p className="footnote">Written by the agent service during the call and saved with the session. Notes summarize topics and confirmed answers, never verbatim speech.</p></section>
 <section className="panel"><span className="eyebrow">SHARED SCRIPT</span><h2>{field?active.section.title+' / '+field.label:'One script. Shared context.'}</h2><p className="muted">{field?.purpose||'The active question and capture guidance appear here.'}</p>{session&&<p className="callout">{active?.spoken_line||session.message}</p>}<details><summary>Capture & clarification guide</summary>{field?<div className="guide"><p><b>Ask:</b> {field.question}</p><p><b>Clarify:</b> {field.clarification}</p><p><b>Validate:</b> {field.validation.description}</p><p><b>Capture:</b> {field.choices?.join(', ')||field.type}</p><p>After {field.max_failed_attempts} failed attempts: human handover.</p></div>:<p>Start a call to view the script.</p>}</details><p className="footnote">{session?.script_version||'energy-demo-v2'} · Draft field assumptions</p></section>
 <section className="panel"><span className="eyebrow">HUMAN HANDOVER</span><h2>{session?.handoff?friendly(session.handoff.reason):'The right person, at the right moment.'}</h2><p className="muted">{session?.handoff?'Energy specialist · '+session.handoff.status:'Confirmed details travel with the conversation.'}</p>{session?.state==='handoff_pending'&&<div className="actions"><button className="primary" disabled={busy||!!session.call_sid} onClick={()=>action('accept')}>Simulate acceptance</button><button disabled={busy} onClick={()=>action('unavailable')}>No specialist</button></div>}<details><summary>Inspect context packet</summary><pre>{session?.handoff?JSON.stringify(session.handoff,null,2):'No handover yet.'}</pre></details></section>
 <section className="panel trace"><span className="eyebrow"><Activity size={14}/> SUPERVISOR TRACE</span><p>{session?.analysis?`${session.analysis.source==='model'?'Contextual model':'Local rules'} · sentiment: ${session.analysis.sentiment} · ${friendly(session.analysis.model_status)}`:session?.mode==='model-assisted'?'Semantic model ready after consent.':'Start a call to see signal analysis.'}</p><div className="signals">{session?.signals.length?session.signals.map((s,i)=><span key={i} title={s.evidence}>{friendly(s.signal)} · {s.source} · turn {s.turn}</span>):<span>No signals detected</span>}</div>{session&&<p className="footnote">{session.mode} · revision {session.revision}<br/>Session: <code>{session.id}</code></p>}</section></aside></div>
 {summary&&<section className="panel record"><div className="panel-heading"><div><span className="eyebrow">CALL RECEIPT</span><h2>{summary.receipt?'Submitted for further processing.':'Call ended. Nothing was submitted.'}</h2></div><Receipt size={22}/></div>
 <div className="record-head"><span>Outcome<strong>{friendly(summary.outcome)}</strong></span><span>Receipt<strong>{summary.receipt?summary.receipt.id:'none issued'}</strong></span><span>Adapter<strong>{summary.receipt?summary.receipt.adapter:'—'}</strong></span><span>Consent<strong>{summary.consent?'given':'not given'}</strong></span></div>
 <div className="record-body"><div><h3>Details</h3>{summary.fields.length?<div className="fields">{summary.fields.map(f=><div className="field" key={f.key}><span>{f.label}</span><strong className="captured">{f.value}</strong></div>)}</div>:<p className="muted">No details were confirmed on this call.</p>}
 <h3>Call notes</h3>{summary.notes.length?<div className="note-console tall">{summary.notes.map((note,i)=><div className={'note '+note.kind} key={i}><span className="note-time">{clock(note.at,started(summary))}</span><span className="note-kind">{NOTE_LABELS[note.kind]||note.kind}</span><p>{note.text}</p></div>)}</div>:<p className="muted">No notes were recorded.</p>}</div>
 <div><h3>Transcript</h3>{summary.transcript.length?<div className="record-transcript">{summary.transcript.map((entry,i)=><div className={'line '+entry.role} key={i}><span className="note-time">{clock(entry.at,started(summary))}</span><small>{entry.role==='caller'?'Caller':'Assistant'}</small><p>{entry.text}</p></div>)}</div>:<p className="muted">Nothing was stored: the caller did not consent.</p>}</div></div>
 <div className="actions"><button className="primary" onClick={download}><Download size={16}/> Download call record</button><button onClick={()=>navigator.clipboard?.writeText(receiptText(summary)).then(()=>setNotice('Call record copied.'),()=>setNotice('Copying is unavailable in this browser.'))}>Copy as text</button></div>
 <p className="footnote">The transcript and notes are saved with the session, and with the receipt when the caller agrees to submit. Caller audio is never recorded. Synthetic demo: no energy plan is purchased or switched.</p></section>}
 <section className="utilities"><details><summary>Restore a session</summary><div className="actions"><input aria-label="Session ID" placeholder="Session ID" value={lookup} onChange={e=>setLookup(e.target.value)}/><button disabled={busy||!lookup.trim()} onClick={load}>Load session</button></div></details><details><summary>Telephone test call</summary><p>Requires configured Twilio credentials and an approved test number. Calling incurs provider charges.</p><div className="actions"><input aria-label="Telephone test number" placeholder="+61400000000" value={number} onChange={e=>setNumber(e.target.value)}/><button disabled={busy||session?.state!=='consent'||session?.dial_attempted||!number} onClick={()=>setDialConfirm(true)}>Prepare call</button></div>{dialConfirm&&<div className="callout">Place a real test call to {number}?<div className="actions"><button className="primary" onClick={dial} disabled={busy}>Place test call</button><button onClick={()=>setDialConfirm(false)}>Cancel</button></div></div>}</details></section>
 <footer><span>Phonease · Energy recovery workspace</span><span>Synthetic journeys · Mock submission</span></footer></main></div></div>;
}
createRoot(document.getElementById('root')).render(<React.StrictMode><App/></React.StrictMode>);
